### ISSUE TITLE
Threads arg in ffmpeg command

### ISSUE THREAD

**Issue by nothingismagick** [keredson/gnomecast#1]
You should be careful where you put the -threads arg in the ffmpeg command. Really sure you need 4 threads to decode? See the answer and the prolific Lord Neckbeards comment here:

https://superuser.com/questions/792525/how-to-change-ffmpeg-threads-settings

**Comment by keredson** [comment]
:+1:  it didn't help anyway.

**Comment by keredson** [comment]
danke!
