### ISSUE TITLE
Error playing DHERBTROHS-462x.yaRulB.p0801_10E10S_gabaelF.mkv

### ISSUE THREAD

**Issue by knireis** [keredson/gnomecast#101]
[Please describe what happened here...]
only black screen
```
[If possible, please run `ffprobe -i <fn>` and paste the output here...]
```

------------------------------------------------------------

File: DHERBTROHS-462x.yaRulB.p0801_10E10S_gabaelF.mkv
Video: Video #1 (h264)
Audio: eng (dts/stereo)
Subtitles: 
Device: QM163E (PHILIPS)
Chromecast: v1.9.5

FileMetadata(fn:/run/user/1000/gvfs/smb-share:server=server,share=server/disk-c/nzb/complete/Fleabag S01E01 (2016) met NL ondertiteling_/DHERBTROHS-462x.yaRulB.p0801_10E10S_gabaelF.mkv, ready:True, thumbnail_fn:/tmp/gnomecast_thumbnail_ybjilibw.jpg, container:mkv, video_streams:[StreamMetadata(index:0:0, codec:h264, title:Video #1)], audio_streams:[AudioMetadata(index:0:1, codec:dts, title:eng, channels:2)], subtitles:[])

```ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x808 [SAR 1:1 DAR 240:101], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, stereo, fltp, 1536 kb/s (default)```

**Comment by keredson** [comment]
can you try again after gnomecast-1.9.6 (and re-open this issue if it's still not playing)?
