### ISSUE TITLE
Error playing Hogans.Heroes.S04E04.DVDRip.XviD.avi

### ISSUE THREAD

**Issue by jorgen4444** [keredson/gnomecast#104]
tv is black nothing coming up, on the source have changed it there, and the application found the tv

```
[If possible, please run `ffprobe -i <fn>` and paste the output here...]
```

------------------------------------------------------------

File: Hogans.Heroes.S04E04.DVDRip.XviD.avi
Video: Video #1 (mpeg4)
Audio: Audio (mp3/stereo)
Subtitles: 
Device: Chromecast (Google Inc.)
Chromecast: v1.9.5

FileMetadata(fn:/media/jorgen/TOSHIBA/Film/Hogans Heroes/Hogans.Heroes.S4.DVDRip/Hogans.Heroes.S04E04.DVDRip.XviD.avi, ready:True, thumbnail_fn:/tmp/gnomecast_thumbnail_6wmhqf2g.jpg, container:avi, video_streams:[StreamMetadata(index:0:0, codec:mpeg4, title:Video #1)], audio_streams:[AudioMetadata(index:0:1, codec:mp3, title:Audio, channels:2)], subtitles:[])

```ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x480 [SAR 1:1 DAR 3:2], 1197 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, stereo, s16p, 192 kb/s
title           : Audio Stream```

**Comment by keredson** [comment]
can you try again after gnomecast-1.9.6 (and re-open this issue if it's still not playing)?
