### ISSUE TITLE
Error playing Modern.Family.S11E03.PROPER.720p.HDTV.x264-KILLERS.mkv

### ISSUE THREAD

**Issue by zgojcic** [keredson/gnomecast#109]
[Please describe what happened here...]

```
[If possible, please run `ffprobe -i <fn>` and paste the output here...]
```

------------------------------------------------------------

File: Modern.Family.S11E03.PROPER.720p.HDTV.x264-KILLERS.mkv
Video: Video #1 (h264)
Audio: Audio #1 (ac3/5.1)
Subtitles: 
Device: Chromecast (Unknown manufacturer)
Chromecast: v1.9.5

FileMetadata(fn:/home/zgojcic/Downloads/Modern.Family.S11E03.PROPER.720p.HDTV.x264-KILLERS/Modern.Family.S11E03.PROPER.720p.HDTV.x264-KILLERS.mkv, ready:True, thumbnail_fn:/tmp/gnomecast_thumbnail_yvosyt8e.jpg, container:mkv, video_streams:[StreamMetadata(index:0:0, codec:h264, title:Video #1)], audio_streams:[AudioMetadata(index:0:1, codec:ac3, title:Audio #1, channels:6)], subtitles:[])

```ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
Stream #0:0: Video: h264 (High), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)```

**Comment by keredson** [comment]
please try again after gnomecast-1.9.6 and re-open this issue if it's still not playing.
