### ISSUE TITLE
Sound not working some videos

### ISSUE THREAD

**Issue by bichomen** [keredson/gnomecast#122]
Some videos do not listen to the audio, I do not know if it has to do with the audio codecs, which ones are supported and which are not?

I use Fedora 32

**Comment by RhFortuna** [comment]
I had the same problem when I did the #124 issue.
This has never happened before, at least using gnomecast.

I use Ubuntu 18.04

**Comment by keredson** [comment]
possible fix in 1.9.9.  (not all chromecast devices support eac3 audio)
