### ISSUE TITLE
Issue with multiple cast devices

### ISSUE THREAD

**Issue by t-vlad** [keredson/gnomecast#135]
Lately, some issue appeared with polling the network for cast sources. Specific error is:
```
Traceback (most recent call last):
  File "/home/vlad/.local/lib/python3.8/site-packages/gnomecast.py", line 563, in f
    friendly_name = cc.device.friendly_name
AttributeError: 'list' object has no attribute 'device'
```
Cause by the fact that pychromecast returns a tuple with 3 items in it, first being the list of chromecasts. Check https://github.com/home-assistant-libs/pychromecast/blob/master/pychromecast/__init__.py#L175 (looks like it changed in this commit: https://github.com/home-assistant-libs/pychromecast/commit/d76c8f1a0130f3b576b829411f07d83504b231bc)
Fix seems to be changing https://github.com/keredson/gnomecast/blob/master/gnomecast.py#L562
from 
`for cc in chromecasts:`
in
`for cc in chromecasts[0]:`
or expanding the returned tuple (Eg: chromecasts, service_browser = pychromecast.get_chromecasts())

I can make a PR if needed

**Comment by acbg** [comment]
This actually seems related to #128

**Comment by t-vlad** [comment]
indeed it is. Sorry about the doubling

**Comment by acbg** [comment]
but the workaround actually works! thank you! I wonder if it'd be compatible with previous AND next versions of pychromecast...
