### ISSUE TITLE
OSError : Cannot assign requested address

### ISSUE THREAD

**Issue by sylvainmetayer** [keredson/gnomecast#15]
I've just installed gnomecast but when I launch it, I've got the following error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/gnomecast", line 11, in <module>
    load_entry_point('gnomecast==0.2.6', 'gui_scripts', 'gnomecast')()
  File "/usr/local/lib/python3.6/site-packages/gnomecast.py", line 719, in main
    caster = Gnomecast()
  File "/usr/local/lib/python3.6/site-packages/gnomecast.py", line 154, in __init__
    s.bind((self.ip, 0))
OSError: [Errno 99] Cannot assign requested address
```

Here is my environment details, if it can help : 

```
Fedora release 27 (Twenty Seven)
NAME=Fedora
VERSION="27 (Workstation Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 27 (Twenty Seven)
Fedora release 27 (Twenty Seven)
```

**Comment by keredson** [comment]
```
(([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + [None])
```

could you tell me  what this give you?

**Comment by sylvainmetayer** [comment]
Here is the result : `['82.216.111.26', None]` (with the import of socket, it wasn't working otherwise)

**Comment by keredson** [comment]
What version of python?  Do you have a local firewall running?

**Comment by sylvainmetayer** [comment]
Python 3.6
I've just switched from Debian to Fedora, and it seems that the firewall policy is quite different. I'll look into it.

**Comment by keredson** [comment]
can you do the following w/o the error?

```python
    with contextlib.closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as s:
      s.bind(('0.0.0.0', 0))
```

**Comment by sylvainmetayer** [comment]
I've disabled the firewall in fedora but still experience the same issue. 
I've tried your code snippet and I've had no output, but no error.

**Comment by fiendish** [comment]
> Here is the result : ['82.216.111.26', None]

82? Your computer has a public IP address? What does ifconfig show?

**Comment by keredson** [comment]
i switched the bind to the universal address for you.  please try v0.2.11 to see if this is fixed.  (prob. it will also error when the HTTP server is binding.  i'd like to see the output for that.)

**Comment by sylvainmetayer** [comment]
Sorry about the delay. 
I've just upgrade to v0.2.15 and it is now working ! Thanks a lot ! :)

**Comment by keredson** [comment]
awesome!  thanks!

**Comment by renich** [comment]
I'm having this issue in Fedora 33; with python3.9 and pretty much the same results when issuing the commands. I get my public IP instead of my local IP.

**Comment by renich** [comment]
I've fixed it by adding an entry to `/etc/hosts`. Basically, 

```
10.0.86.99 mydesktop.local mydesktop
```
So that gnomecast can get the proper IP. Now, it gets the internal IP; not the public one.
