### ISSUE TITLE
inhibit screensaver?

### ISSUE THREAD

**Issue by keredson** [keredson/gnomecast#17]
should we inhibit the screensaver while casting?  looking for opinons.  the purpose would be to keep the play/pause controls available while watching something.

possible mechanism:
https://stackoverflow.com/questions/10885337/inhibit-screensaver-with-python

**Comment by sdushantha** [comment]
Not sure what you mean. Could you possibly show an example?

**Comment by fiendish** [comment]
I figure if someone wants to inhibit their screen locking, they can use something like https://extensions.gnome.org/extension/1097/keep-awake/

**Comment by keredson** [comment]
i mean if you're watching something on the TV, and your controls are on your computer, it's annoying to have to unlock your computer to pause the TV.  i was thinking it would only inhibit the screen saver if the video's actually playing.

**Comment by sdushantha** [comment]
Yeah, this would be a good idea! 👍
