### ISSUE TITLE
support chromecast audio

### ISSUE THREAD

**Issue by ibotty** [keredson/gnomecast#2]
Does it support chromecast audio?

**Comment by phoe** [comment]
I'd like this to stream music in various formats to my Chromecast. That question is important to me.

**Comment by tobiasboyd** [comment]
I can confirm that it currently discovers audio-only devices, it finds my Chromecast Audio and gHome Mini, but since it only wants to stream video files to them, that's not terribly useful (I could transcode mp3 to mp4 for that, but it'd be a lot of extra work).

**Comment by keredson** [comment]
`gnomecast-0.2.0` released w/ `wav`/`aac`/`mp3` support!
