### ISSUE TITLE
Add the GnomeCast logo to the title?

### ISSUE THREAD

**Issue by sdushantha** [keredson/gnomecast#20]
Would it be cool if we added the GnomeCast logo in the title?

# GnomeCast![gnomecast_48](https://user-images.githubusercontent.com/27065646/36344885-4c2a0c54-1421-11e8-8833-5d51acb86b24.png)

Should somehow make the image move down to aline with the text.

**Comment by keredson** [comment]
done! https://github.com/keredson/gnomecast/commit/2432555710359f99f24c95958fe01f20116c261d
