### ISSUE TITLE
Desktop app name should be GnomeCast not Gnomecast

### ISSUE THREAD

**Issue by sdushantha** [keredson/gnomecast#21]
Here is the app name in the launcher
![screenshot from 2018-02-18 17-26-35](https://user-images.githubusercontent.com/27065646/36354216-2af0484a-14d1-11e8-9519-8cb1b63531de.png)

And here is the app name on the app
![screenshot from 2018-02-18 17-27-08](https://user-images.githubusercontent.com/27065646/36354235-7565454c-14d1-11e8-9669-13c945fa32b7.png)

Not sure how to change that. But would be nice if you could tell me how so I can learn something new :)

**Comment by keredson** [comment]
Hmm.  Google doesn't appear to capitalize the c in Chromecast.  It should all be Gnomecast not GnomeCast.

Awesome if you're getting into programming! All the references to the names are going to be in either `gnomecast.py` or `gnomecast.desktop` if you want to fix.

**Comment by sdushantha** [comment]
So should I just fix the name ```GnomeCast``` to ```Gnomecast``` on the README.md and the title part of the window?

**Comment by keredson** [comment]
That works for me!

**Comment by sdushantha** [comment]
@keredson and also, could you please check my PR thath i made 23 hours ago?

**Comment by keredson** [comment]
Fixed in #22

**Comment by sara-rodriguez** [comment]
my gnomecast didn't appear on the launcher, I've tried everything :-(
