### ISSUE TITLE
New screenshot with the new title?

### ISSUE THREAD

**Issue by sdushantha** [keredson/gnomecast#23]
Not sure if this necessary, but replacing the screen shot with the title GnomeCast with a new one would be nice because it is not called GnomeCast anymore.

**Comment by keredson** [comment]
done

**Comment by keredson** [comment]
i also changed the image size down to 600.  i think you'd suggested the same change somewhere.  i had made it that large to make sure the boarders didn't show, but added some resize calls now to get the same effect w/ a smaller thumbnail.
