### ISSUE TITLE
Make a contribution list

### ISSUE THREAD

**Issue by sdushantha** [keredson/gnomecast#32]
Since we've got 5 people contributing to this project, I feel like it is time we put list of the contributers in the README.md

We should use this [all contributors](https://github.com/kentcdodds/all-contributors) method to show the contributors of gnomecast.

**Comment by keredson** [comment]
what's wrong w/ the one GH provides?  https://github.com/keredson/gnomecast/graphs/contributors

**Comment by sdushantha** [comment]
nothing wrong with it. just thought might be nice since other open source projects do so.

**Comment by keredson** [comment]
that looks like it needs to be manually maintained, plus GH already calcs that for us.  so going to pass.  thanks tho!
