### ISSUE TITLE
Error when installing in a virtual environment: ImportError: No module named 'gi'

### ISSUE THREAD

**Issue by metteludwig** [keredson/gnomecast#4]
Got the error in the title on `pip3 install gnomecast`. 

Traced it down to the following:
Because I first created a virtual environment with `mkvirtualenv -p /usr/bin/python3 gnomecastenv`, I accidentally excluded the system wide packages, including gtk and gi. 
If running inside a virtual environment, system wide packages are not included by default. By building the environment with "--system-site-packages" everything works.

This is already solved, so I'm just putting this here to help any other folks trying to work it in a virtual environment.

**Comment by keredson** [comment]
added to the docs, thanks!
