### ISSUE TITLE
Casting fails with repeated "waiting for transcode to finish" linux mint 18.3

### ISSUE THREAD

**Issue by sethspoel** [keredson/gnomecast#48]
My deepest apologies for being the sort of Linux user that knows barely enough to be dangerous, but I'm very interested in using this tool. I had some trouble with the Python 3 dependencies, but I think I worked through them--though when I finally got a working copy of gnomecast to install, I received a "failed to build wheel" error for gnomecast and several dependencies. Launching gnomecast finds my chromecast device, and I can choose an .mkv file to stream, but transcoding makes no progress (remains at zero percent) and receive endless "waiting for transcode to finish" messages in the command window. Choosing an .m4v file works as expected

**Comment by keredson** [comment]
> My deepest apologies for being the sort of Linux user that knows barely enough to be dangerous

no need for that.  we're all been there.  :)

could you post the full output of gnomecast for the file that won't transcode?  also if possible a magnet link to the .mkv file?

very weird that it would work on an .m4v file but not an .mkv.  (they both require transcoding.)

**Comment by sethspoel** [comment]
I'm pretty sure I figured it out. I tried some other .mkv files and they all worked. I noticed (I did not name these files!) that the one that failed had an apostrophe in the file name. I renamed the file to remove the apostrophe and transcoding worked as expected. Brilliant, by the way.

**Comment by keredson** [comment]
well it should be able to handle all the filenames.  :)

hmm, i just tested `BigBuck'Bunny.mkv`, and it transcoded fine.

if you're able to post the commandline logs, i'll look into it further.  otherwise, feel free to close the issue.  thanks!

**Comment by keredson** [comment]
hopefully pr #49 is the fix for this.
