### ISSUE TITLE
automatically find a subtitles file with the same name as the Video

### ISSUE THREAD

**Issue by k3ck3c** [keredson/gnomecast#51]
Hello

Thanks for this great tool.

If a video file and a .srt file have the same name, is it possible, after choosing the video file, to offer as default file for the subtitles, the associated subtitle file?

Example

$ ll 800*_6*
-rw-r--r-- 1 gg gg 367257633 avril 16 19:30 800_Words_Series_1_-_6._Episode_6_b08vl92r_original.mp4
-rw-r--r-- 1 gg gg     88911 avril 16 19:30 800_Words_Series_1_-_6._Episode_6_b08vl92r_original.srt

If I select as video file

800_Words_Series_1_-_6._Episode_6_b08vl92r_original.mp4

and 

800_Words_Series_1_-_6._Episode_6_b08vl92r_original.srt

exists, then propose this file by default.

Regards

**Comment by e-ht** [comment]
This would be a pretty neat feature.  I'll see if I can add a PR this weekend.

**Comment by k3ck3c** [comment]
This is debatable, but, if the choosen video file is /home/$USER/Videos/myfile.mkv, launch for choosing the subtitles file,  gtkFileChooser with a default directory of /home/$USER/Videos

**Comment by keredson** [comment]
Agreed.  And the dir default is already in the latest version!

**Comment by keredson** [comment]
merged, thanks!
