### ISSUE TITLE
Shutting down kills other stream

### ISSUE THREAD

**Issue by pilophae** [keredson/gnomecast#57]
Steps to reproduce:
1. Start streaming with Gnomecast.
2. Stop streaming with Gnomecast, but keep application on.
3. Start streaming with another application towards the same Chromecast.
4. Shut down Gnomecast.

Expected behaviour:
The new stream continues.

Actual behaviour:
The new stream is aborted.

**Comment by keredson** [comment]
yeah, that's not ideal.  i'm surprised the chromecast is willing to listen to a stop command from the original app after a new running app has come up.  will do some testing.

**Comment by keredson** [comment]
confirmed the behavior.

**Comment by keredson** [comment]
i don't know how to check to see if we're still playing or something else is, but the command we send to stop playback really isn't necessary, so i just removed it.  if the file we've deleted isn't there anymore well OK, the chromecast will stop anyway when it runs out of buffer.
