### ISSUE TITLE
We need a logo for GnomeCast

### ISSUE THREAD

**Issue by sdushantha** [keredson/gnomecast#6]
maybe a mix of the gnome logo and chromecast logo

**Comment by ogrim** [comment]
Wanted to make the same fix myself :) 👍

**Comment by mirorauhala** [comment]
Did this quickly...
<img width="399" alt="screen shot 2018-02-16 at 17 34 24" src="https://user-images.githubusercontent.com/4082806/36315243-d18222d4-133f-11e8-8aca-01946bec67f2.png">

**Comment by keredson** [comment]
![image](https://user-images.githubusercontent.com/2049665/36323335-2debc95a-1316-11e8-8049-c0595d43252e.png)
![image](https://user-images.githubusercontent.com/2049665/36323352-426074da-1316-11e8-9125-13779e886fbb.png)
