### ISSUE TITLE
Firewall settings

### ISSUE THREAD

**Issue by slumbergod** [keredson/gnomecast#62]
I'd like to add the appropriate rules for firewall (GUFW) but I have not been able to find any reference to the correct ports. As it currently stands, I have to disable my firewall to cast from Gnomecast or VLC3. Has anyone successfully added rules to their firewall?

**Comment by keredson** [comment]
this might be of use: https://blog.g3rt.nl/allow-google-chromecast-host-firewall-iptables.html

**Comment by slumbergod** [comment]
I've been having more problems with gnomecast and I finally managed to get a hold of chromecast support. I requested the details of what ports to open and they sent this:

Ports:
Outgoing UDP Multicast on port 1900 and 5353
Incoming UDP Unicast on arbitrary ports > 53 and 123
Outgoing HTTP on port 8008, 8009, 80 and 443

DNS:
Chromecast uses the following Google public DNS addresses:
8.8.8.8
8.8.4.4 

Maybe it will help.

**Comment by PhotonQyv** [comment]
@slumbergod Don't know if you've now got it sorted out, after all your last comment was from January 2020, but I've just checked my UFW rules, and I have the following set up specifically for my Chromecast:

32768:60999/udp ALLOW IN 192.168.0.23
32768:60999/tcp ALLOW IN 192.168.0.23
1900/udp ALLOW IN 192.168.0.23

Where 192.168.0.23 is my Chromecast's local network IP address.

So long as I turn off the VPN I use normally, I can stream via Gnomecast to the Chromecast with the UFW Firewall on perfectly fine.

My UFW is set to DENY incoming by default, while ALLOW-ing outgoing by default, so perhaps if I disallowed outgoing stuff I'd need some more rules using some of the outgoing ports you mention.

But, as I say, the above rules work perfectly for me.

Hope this helps, if not you, then someone else who comes looking for help with streaming through UFW.

**Comment by slumbergod** [comment]
I'd actually given up trying and just disabled UFW. I'll give your rules a try though.

Do you need to set up a static IP address for your Chromecast?

**Comment by PhotonQyv** [comment]
@slumbergod I've got it set up so that both my laptop which I stream from and the Chromecast have set, defined IP (leased) addresses assigned by my hub/router, so that the UFW rules can be made a little more specific, after all what's the point in having a firewall if I then allow anything to connect to those ports, and not just the Chromecast.

Incidentally, if you want to try to see if VLC will do the job:

8010 ALLOW IN 192.168.0.23

Where 8010 is the default port that VLC uses to stream.

Again, hope that helps. Incidentally, I use sudo gufw to actually create the rules, as I've not quite got my head around doing it on the command-line using ufw.

**Comment by slumbergod** [comment]
@ PhotonQyv thanks. I have started experimenting. Our router has some strange quirks so it'll be one challenge at a time. I hope I can get it done though. Cheers!

**Comment by PhotonQyv** [comment]
@slumbergod No worries, I wish I could recall where I got my info from, and I'd put a link in a reply to you, but it's been a while since I got it sorted out and working. Good luck with it (:*

**Comment by slumbergod** [comment]
In case anyone else experiences this I found the solution. This worked under Xubuntu and Manjaro.
1. Assign a permanent IP address for your chrome cast device on your network.
2. Using the command line, just enter this command: sudo ufw allow from x.x.x.x
where x.x.x.x is the IP address you gave to the chromecast.
