### ISSUE TITLE
Package dependencies are broken (and/or prerequesits missing from README)

### ISSUE THREAD

**Issue by atleta** [keredson/gnomecast#74]
Trying to install into a virtualenv with pip results in:
```
  Using cached https://files.pythonhosted.org/packages/5e/4c/748b9cbdfe5e3cffd29e90b088a19f723ed51e00eafd4bcbec4abf089386/gnomecast-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    No module named 'pychromecast'
    No module named 'dbus'
    
    ----------------------------------------------------------------------
    Python package "gi" (for building the GU not found.
    
    If on Debian or Ubuntu, please run:
    $ sudo apt-get install python3-gi
    
    For other distributions please look up the equivalent package.
    
    If this doesn't work, please report the error here:
    https://github.com/keredson/gnomecast
    
    Thanks! - Gnomecast
    ----------------------------------------------------------------------
    
    Traceback (most recent call last):
      File "/tmp/pip-install-f31a21kr/gnomecast/gnomecast.py", line 19, in <module>
        import pychromecast
    ImportError: No module named 'pychromecast'
    
    ----------------------------------------
```

The solution (for now) is:
1. install external dependency `python3-gi` (it is actually suggested by the setup script if missing)
2. `pip install bottle pychromecast pydbus gnomecast` (the first three should really be auto-installed)

**Comment by atleta** [comment]
Also, the README says "If installing in a mkvirtualenv built virtual environment, make sure you include the --system-site-packages parameter" and it's a bit misleading as it sounds as if it's only needed for mkvirtualenv, while (at least it seems) it's needed with whatever virtualenv. So probably better say that.

**Comment by atleta** [comment]
I'm not willing to install it globally (i.e. outside of a virtualenv), but why does it matter?

**Comment by keredson** [comment]
Global is needed for the gnome shell integration.  It does work without it
tho.

It looks like you need to either install or enable "sudo apt-get install
python3-gi" in your virtual env. Did you try that?

Can you tell me what was the command you ran?

**Comment by keredson** [comment]
added `python3-gi` to the docs
