### ISSUE TITLE
Failed to cast to my device if internet is not available

### ISSUE THREAD

**Issue by arulrajnet** [keredson/gnomecast#77]
Here is my environment

* My device connected wired with my router
* My PC connected wired with my router
* WAN / Internet is not available

In gnomecast my device got detected and I selected the video file its converted 100%. Then I play the video. Its doesn't play that. The same was working while WAN connectivity is available.

**Comment by keredson** [comment]
Specific to this file or all files?

**Comment by keredson** [comment]
i hit this myself today.  it appears chromecast win't play w/o internet, even tho it's streaming locally.  nothing can be done tho i don't think.
