### ISSUE TITLE
Fail to overwrite original file with transcoded version

### ISSUE THREAD

**Issue by didierga** [keredson/gnomecast#79]
My configuration is the following:

Fedora 4.19.11-300.fc29.x86_64
Gnomecast v1.7.0
/var/tmp is on partition / on device /dev/sdb3 (ssd)
/home/azerty is on partition /home on device /dev/sda4 (hdd)

When I I try to overwrite original file with transcoded version I get this error:

`gnomecast.py:698:save_transcoded_file:OSError: [Errno 18] Invalid cross-device link: '/var/tmp/gnomecast_o8ss9cmz.mp4' -> '/home/azerty/Work/test2del.mp4'`

By the way, what are the original file specifications who trigger gnomecast to transcode file or what are acceptable specifications to cast original file without need to transcode it ?
I use a Chromecast Ultra compatible 4K HDR.

**Comment by keredson** [comment]
Thanks for the bug report!

For the second part: it has to be an mp4 container, with h264 or h265 video
encoding, and mp3 or aac audio.  Almost all videos are encoded right, so
usually it's just reboxing.

**Comment by keredson** [comment]
i took this feature out because the transcoded file loses info.  (subtitles, other a/v streams, etc.)

**Comment by ckrzen** [comment]
< Remove File > button still has tool-tip for non-existent feature: "Overwrite original file with transcoded version."

**Comment by keredson** [comment]
you're seeing that button in what version?  i thought i took the whole thing out.

**Comment by ckrzen** [comment]
v1.9.5

When I hover over the "Minus" button, below the "Plus" button, when there is at least one file in the queue.


Oct 9, 2019, 15:39 by notifications@github.com:

**Comment by ckrzen** [comment]
I couldn't figure out how to keep the tooltip visible for a screenshot, so I did a screencast video to demonstrate.

I'm using "Firefox Send"(send.firefox.com) to post this to you, but the link will expire in 7-days(maximum allowed): 

https://send.firefox.com/download/e67472873648cd05/#tR3HLORNz8bU9Xqg_fC-EA

HTH!
