### ISSUE TITLE
Is reaching out to public DNS necessary?

### ISSUE THREAD

**Issue by e-ht** [keredson/gnomecast#81]
I'm under the impression Casting is only available via private net which makes me curious why the need to reach out to a public DNS server on line 212 (https://github.com/keredson/gnomecast/blob/master/gnomecast.py#L212).

` self.ip = (([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + [None])[0]`

**Comment by e-ht** [comment]
Ergh... #77

**Comment by keredson** [comment]
It just hits it here to get a non local ip/port combination.  Possible we could engineer this out, but as the Chromecast won't play without internet anyway... (Google's gotta phone home!  They're sell these things cheap for a reason!!! ;)
