### ISSUE TITLE
Audio needs transcoding if not stereo

### ISSUE THREAD

**Issue by horiakr** [keredson/gnomecast#82]
If the audio stream of the file is using the correct format but the number of channels is not 'stereo', but 5.1 or another, then Chromecast fails to play the file.

I have the new Chromecast - generation 3 - and audio other than in 'stereo' fails playback.

Detection of number of channels would be needed when loading the file, and enforcing of audio transcoding would be required if channels of audio stream is not 'stereo'.

`ffmpeg -i` example for an audio stream containing 5.1 sound:
`Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 382 kb/s (default)`
and stereo:
`Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 124 kb/s (default)`

For this purpose, there are multiple formulas and methods to combine the 5 or 7 channels to a stereo downmix. [See here](https://superuser.com/questions/852400/properly-downmix-5-1-to-stereo-using-ffmpeg) for some ffmpeg suggestions on how to downmix.

**Comment by keredson** [comment]
turns out chromecast can't do anything >2 channels in aac.  only ac3.  just added transcoding from multi-channel aac to ac3 in v1.8.0.  also now 5.1 surround works.
