### ISSUE TITLE
Incorrect subtitles found in mkv

### ISSUE THREAD

**Issue by jleclanche** [keredson/gnomecast#88]
I used [mkvtoolnix](https://mkvtoolnix.download/) to merge in 5 subtitle tracks into an mkv: english, french, swedish, portuguese 2x (pt-pt and pt-br, but mkv only has `por`).

![image](https://user-images.githubusercontent.com/235410/52535770-a1679880-2d52-11e9-85b1-5e8f71026c08.png)

But even after giving each subtitle track a name, all I see is "0.3", "0.4", "0.5", "0.6" and "0.7". And the other problem is that no matter which one I choose, it always casts English subtitles (the default subtitle track).

![image](https://user-images.githubusercontent.com/235410/52535720-18e8f800-2d52-11e9-82cc-ace1f4bcad39.png)

**Comment by keredson** [comment]
agreed this is highly annoying.  i haven't found a way to get ffmpeg to give me the subtitle names.  if you have suggestions i'm all ears.  :)

**Comment by keredson** [comment]
fixed the name extraction.  can you link to the file you're getting the selection problem with?

**Comment by keredson** [comment]
also figured out the selection problem.  fixed in v1.9.2.
