### ISSUE TITLE
[Proposal] Codebase Refactor

### ISSUE THREAD

**Issue by rgegriff** [keredson/gnomecast#90]
I was considering splitting the Gnomecast class up into different files to make it a little bit easier to digest and extend. The general architecture I was considering was to split things into UI, application state, bottle app, media management (kind of already handled with the Transcoder class), and chromecast handling.

If I put the time in to do that, and submitted a PR, would you be interested in merging it in? Or is the single python file preferred for this project?

**Comment by keredson** [comment]
i'd be fine with that.  i would also like to get more of the state for each file out of the liststore (having one media state object - possibly just an expanded transcoder obj - in the liststore).  subtitles need to be integrated into that as well.

would request multiple smaller PRs (at min one per file being pulled out, but whatever makes sense).

this also needs automated testing...

**Comment by rgegriff** [comment]
I started with something simple, https://github.com/keredson/gnomecast/pull/91/files that pulls the `Transcode` class out into it's own file.

I think eventually it will make sense to move things to an `src/` directory, but I didn't feel like messing with setup.py in this PR

Testing is a good idea, It will be fun to figure out how to test the transcode process and the UI portions. Everything else seems pretty straightforward to test.

**Comment by keredson** [comment]
I'd considered creating short 2s video files that would be small enough to check in (and be covered under fair use).

**Comment by keredson** [comment]
someone else did this too, and i merged it, but i just undid it because of deploy problems some people were having.  think i'm going to keep it single-file for now, even tho it's passed 1k LOC.
