### ISSUE TITLE
Support Chromecast offline

### ISSUE THREAD

**Issue by lfdominguez** [keredson/gnomecast#94]
Hello i will testing the Chromecast in a place without internet, so reading the Chromecast Help seems that i need connect to it Hot-Spot Wifi and type a code on the App, but i dont see any of these capabilities on gnomecast, is that correct??

**Comment by keredson** [comment]
chromecast's can't work offline.  they need at least a minimal connection even to support local streaming.  they should work with a hotspot, but you'd configure that during the chromecast setup through google's app (google home?), not during usage / streaming.
