### ISSUE TITLE
Subtitles appears on TOP

### ISSUE THREAD

**Issue by otavioschwanck** [keredson/gnomecast#95]
How can i configure the subtitles position ?

**Comment by keredson** [comment]
At the top?  That's bizarre.  Can you take a picture?

**Comment by horva** [comment]
I'm also having the same issue. 
![IMG_20190702_001448](https://user-images.githubusercontent.com/2076080/60469944-bfc92480-9c5e-11e9-8a7b-e8319cafab46.jpg)

**Comment by keredson** [comment]
is this all files you're casting or some in particular?

**Comment by horva** [comment]
I tried to understand your question by reading it 20 times but I'm still confused :) I think this might be related to ChromeCast firmware update (it also messed up Videostream), my current ChromeCast firmware version is: 1.40.156414

**Comment by Talv** [comment]
Yeah, I've experienced the same few days ago, when trying gnomecast for the first time. After some googling it does seem to be firmware related: https://support.google.com/chromecast/thread/7612416?msgid=9069749
If it is the same issue, it might be fixed as of today. I personally can't test at the moment.

**Comment by wseabra** [comment]
I've installed gnomecast today and I'm having this same problem. Is there a workaround for this?

**Comment by damiantundis** [comment]
I'm also having the same problem.

**Comment by Reggino** [comment]
This is definitely a firmware thing: i'm having 2 Chromecasts. My older Chromcast shows the subtitles properly at the bottom. My newer Chromecast shows it at the top... 

Weird.

**Comment by keredson** [comment]
Yeah I've noticed this too recently.  There isn't any option to configure the position.  Hopefully Google can work this out eventually.

**Comment by mariantatarau90** [comment]
The same for me, subtitle is on top

**Comment by esmin** [comment]
Subtitle position is now fine after latest firmware update - 1.42.168007 (2nd gen)
By the way, I'm using Preview Program firmware version - just to confirm it was Chromecast issue.

**Comment by keredson** [comment]
Thanks all.  This is definitely a chromecast bug - I've seen it on my personal one as well.  There's nothing in the DefaultMediaReceiver API I've seen that can control subtitle placement.  Closing as there is nothing I can do.
